- peg-
- ppg-
- dea-
- mipa-
- edta-
- thicone
- siloxane
- chlorexidine
- petrolatum
- paraffinum liquidum
- carbomer
- crosspolymer
- acrylate
- styrene
- copolymer
- triethanolamine
- triclosan
- dmdm
- hydantoin
- imidazolidinyl urea
- diazolidinyl urea
- formaldheyde
- methylchloroisothiazolinone
- methylisothiazolinone
- sodium hydroxymethylglycinate
- nonoxynol
- poloxamer
- trimonium
- dimonium
- glycol
- glicol
